src/com/serotonin/mango/vo/report/ReportCsvStreamer.java
/*
    Mango - Open Source M2M - http://mango.serotoninsoftware.com
    Copyright (C) 2006-2011 Serotonin Software Technologies Inc.
    @author Matthew Lohbihler
    
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.serotonin.mango.vo.report;

import java.io.PrintWriter;
import java.util.ResourceBundle;

import org.joda.time.DateTime;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;

import com.serotonin.mango.view.export.CsvWriter;
import com.serotonin.mango.view.text.TextRenderer;
import com.serotonin.web.i18n.I18NUtils;

/**
 * @author Matthew Lohbihler
 */
public class ReportCsvStreamer implements ReportDataStreamHandler {
    private final PrintWriter out;

    // Working fields
    private TextRenderer textRenderer;
    private final String[] data = new String[5];
    private final DateTimeFormatter dtf = DateTimeFormat.forPattern("yyyy/MM/dd HH:mm:ss");
    private final CsvWriter csvWriter = new CsvWriter();

    public ReportCsvStreamer(PrintWriter out, ResourceBundle bundle) {
        this.out = out;

        // Write the headers.
        data[0] = I18NUtils.getMessage(bundle, "reports.pointName");
        data[1] = I18NUtils.getMessage(bundle, "common.time");
        data[2] = I18NUtils.getMessage(bundle, "common.value");
        data[3] = I18NUtils.getMessage(bundle, "reports.rendered");
        data[4] = I18NUtils.getMessage(bundle, "common.annotation");
        out.write(csvWriter.encodeRow(data));
    }

    public void startPoint(ReportPointInfo pointInfo) {
        data[0] = pointInfo.getExtendedName();
        textRenderer = pointInfo.getTextRenderer();
    }

    public void pointData(ReportDataValue rdv) {
        data[1] = dtf.print(new DateTime(rdv.getTime()));

        if (rdv.getValue() == null)
            data[2] = data[3] = null;
        else {
            data[2] = rdv.getValue().toString();
            data[3] = textRenderer.getText(rdv.getValue(), TextRenderer.HINT_FULL);
        }

        data[4] = rdv.getAnnotation();

        out.write(csvWriter.encodeRow(data));
    }

    public void done() {
        out.flush();
        out.close();
    }
}

src/com/serotonin/mango/vo/report/ReportInstance.java
/*
    Mango - Open Source M2M - http://mango.serotoninsoftware.com
    Copyright (C) 2006-2011 Serotonin Software Technologies Inc.
    @author Matthew Lohbihler
    
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.serotonin.mango.vo.report;

import java.util.ResourceBundle;

import org.joda.time.DateTime;

import com.serotonin.mango.Common;
import com.serotonin.mango.util.DateUtils;
import com.serotonin.web.i18n.I18NUtils;
import com.serotonin.web.taglib.DateFunctions;

/**
 * @author Matthew Lohbihler
 */
public class ReportInstance {
    public static final int STATE_NOT_STARTED = 1;
    public static final int STATE_STARTED = 2;
    public static final int STATE_FINISHED = 3;
    public static final int STATE_FAILED = 4;

    private int id = Common.NEW_ID;
    private int userId;
    private String name;
    private int includeEvents;
    private boolean includeUserComments;
    private long reportStartTime = -1;
    private long reportEndTime = -1;
    private long runStartTime = -1;
    private long runEndTime = -1;
    private int recordCount = -1;
    private boolean preventPurge;

    private ResourceBundle bundle;

    public ReportInstance() {
        // no op
    }

    public ReportInstance(ReportVO template) {
        userId = template.getUserId();
        name = template.getName();
        includeEvents = template.getIncludeEvents();
        includeUserComments = template.isIncludeUserComments();

        if (template.getDateRangeType() == ReportVO.DATE_RANGE_TYPE_RELATIVE) {
            if (template.getRelativeDateType() == ReportVO.RELATIVE_DATE_TYPE_PREVIOUS) {
                DateTime date = DateUtils.truncateDateTime(new DateTime(), template.getPreviousPeriodType());
                reportEndTime = date.getMillis();
                date = DateUtils.minus(date, template.getPreviousPeriodType(), template.getPreviousPeriodCount());
                reportStartTime = date.getMillis();
            }
            else {
                DateTime date = new DateTime();
                reportEndTime = date.getMillis();
                date = DateUtils.minus(date, template.getPastPeriodType(), template.getPastPeriodCount());
                reportStartTime = date.getMillis();
            }
        }
        else {
            if (!template.isFromNone()) {
                DateTime date = new DateTime(template.getFromYear(), template.getFromMonth(), template.getFromDay(),
                        template.getFromHour(), template.getFromMinute(), 0, 0);
                reportStartTime = date.getMillis();
            }

            if (!template.isToNone()) {
                DateTime date = new DateTime(template.getToYear(), template.getToMonth(), template.getToDay(), template
                        .getToHour(), template.getToMinute(), 0, 0);
                reportEndTime = date.getMillis();
            }
        }
    }

    public int getState() {
        if (runStartTime == -1)
            return STATE_NOT_STARTED;
        if (runEndTime == -1)
            return STATE_STARTED;
        if (recordCount == -1)
            return STATE_FAILED;
        return STATE_FINISHED;
    }

    public void setBundle(ResourceBundle bundle) {
        this.bundle = bundle;
    }

    public boolean isFromInception() {
        return reportStartTime == -1;
    }

    public boolean isToNow() {
        return reportEndTime == -1;
    }

    public String getPrettyReportStartTime() {
        if (reportStartTime == -1)
            return I18NUtils.getMessage(bundle, "common.inception");
        return DateFunctions.getFullMinuteTime(reportStartTime);
    }

    public String getPrettyReportEndTime() {
        if (reportEndTime == -1)
            return I18NUtils.getMessage(bundle, "reports.now");
        return DateFunctions.getFullMinuteTime(reportEndTime);
    }

    public String getPrettyRunStartTime() {
        if (runStartTime == -1)
            return I18NUtils.getMessage(bundle, "reports.notStarted");
        return DateFunctions.getFullMinuteTime(runStartTime);
    }

    public String getPrettyRunEndTime() {
        if (runStartTime == -1)
            return "";
        if (runEndTime == -1)
            return I18NUtils.getMessage(bundle, "reports.inProgress");
        return DateFunctions.getFullMinuteTime(runEndTime);
    }

    public String getPrettyRunDuration() {
        if (runStartTime == -1)
            return "";
        if (runEndTime == -1)
            return I18NUtils.getMessage(bundle, "reports.inProgress");
        return DateUtils.getDuration(runEndTime - runStartTime).getLocalizedMessage(bundle);
    }

    public String getPrettyRecordCount() {
        if (runStartTime == -1)
            return "";
        if (runEndTime == -1)
            return "";
        if (recordCount == -1)
            return I18NUtils.getMessage(bundle, "reports.failed");
        return Integer.toString(recordCount);
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getIncludeEvents() {
        return includeEvents;
    }

    public void setIncludeEvents(int includeEvents) {
        this.includeEvents = includeEvents;
    }

    public boolean isIncludeUserComments() {
        return includeUserComments;
    }

    public void setIncludeUserComments(boolean includeUserComments) {
        this.includeUserComments = includeUserComments;
    }

    public long getReportStartTime() {
        return reportStartTime;
    }

    public void setReportStartTime(long reportStartTime) {
        this.reportStartTime = reportStartTime;
    }

    public long getReportEndTime() {
        return reportEndTime;
    }

    public void setReportEndTime(long reportEndTime) {
        this.reportEndTime = reportEndTime;
    }

    public long getRunStartTime() {
        return runStartTime;
    }

    public void setRunStartTime(long runStartTime) {
        this.runStartTime = runStartTime;
    }

    public long getRunEndTime() {
        return runEndTime;
    }

    public void setRunEndTime(long runEndTime) {
        this.runEndTime = runEndTime;
    }

    public int getRecordCount() {
        return recordCount;
    }

    public void setRecordCount(int recordCount) {
        this.recordCount = recordCount;
    }

    public boolean isPreventPurge() {
        return preventPurge;
    }

    public void setPreventPurge(boolean preventPurge) {
        this.preventPurge = preventPurge;
    }
}

src/com/serotonin/mango/vo/report/ReportUserComment.java
/*
    Mango - Open Source M2M - http://mango.serotoninsoftware.com
    Copyright (C) 2006-2011 Serotonin Software Technologies Inc.
    @author Matthew Lohbihler
    
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.serotonin.mango.vo.report;

import com.serotonin.web.taglib.DateFunctions;

public class ReportUserComment {
    private String username;
    private int commentType;
    private int typeKey;
    private String pointName;
    private long ts;
    private String comment;

    public String getPrettyTime() {
        return DateFunctions.getTime(ts);
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public int getCommentType() {
        return commentType;
    }

    public void setCommentType(int commentType) {
        this.commentType = commentType;
    }

    public int getTypeKey() {
        return typeKey;
    }

    public void setTypeKey(int typeKey) {
        this.typeKey = typeKey;
    }

    public String getPointName() {
        return pointName;
    }

    public void setPointName(String pointName) {
        this.pointName = pointName;
    }

    public long getTs() {
        return ts;
    }

    public void setTs(long ts) {
        this.ts = ts;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }
}

src/com/serotonin/mango/web/mvc/controller/ReportChartController.java
/*
    Mango - Open Source M2M - http://mango.serotoninsoftware.com
    Copyright (C) 2006-2011 Serotonin Software Technologies Inc.
    @author Matthew Lohbihler
    
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.serotonin.mango.web.mvc.controller;

import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.springframework.web.servlet.ModelAndView;
import org.springframework.web.servlet.View;
import org.springframework.web.servlet.mvc.AbstractController;

import com.serotonin.mango.Common;
import com.serotonin.mango.db.dao.ReportDao;
import com.serotonin.mango.vo.User;
import com.serotonin.mango.vo.permission.Permissions;
import com.serotonin.mango.vo.report.ReportChartCreator;
import com.serotonin.mango.vo.report.ReportChartCreator.PointStatistics;
import com.serotonin.mango.vo.report.ReportInstance;

/**
 * @author Matthew Lohbihler
 */
public class ReportChartController extends AbstractController {
    @Override
    protected ModelAndView handleRequestInternal(HttpServletRequest request, HttpServletResponse response)
            throws Exception {

        int instanceId = Integer.parseInt(request.getParameter("instanceId"));
        ReportDao reportDao = new ReportDao();
        ReportInstance instance = reportDao.getReportInstance(instanceId);

        User user = Common.getUser(request);
        Permissions.ensureReportInstancePermission(user, instance);

        ReportChartCreator creator = new ReportChartCreator(ControllerUtils.getResourceBundle(request));
        creator.createContent(instance, reportDao, null, false);

        Map<String, byte[]> imageData = new HashMap<String, byte[]>();
        imageData.put(creator.getChartName(), creator.getImageData());
        for (PointStatistics pointStatistics : creator.getPointStatistics())
            imageData.put(pointStatistics.getChartName(), pointStatistics.getImageData());
        user.setReportImageData(imageData);

        return new ModelAndView(new ReportChartView(creator.getHtml()));
    }

    static class ReportChartView implements View {
        private final String content;

        public ReportChartView(String content) {
            this.content = content;
        }

        public String getContentType() {
            return null;
        }

        public void render(Map model, HttpServletRequest request, HttpServletResponse response) throws Exception {
            response.getWriter().write(content);
        }
    }
}

src/com/serotonin/mango/web/servlet/ReportChartServlet.java
/*
    Mango - Open Source M2M - http://mango.serotoninsoftware.com
    Copyright (C) 2006-2011 Serotonin Software Technologies Inc.
    @author Matthew Lohbihler
    
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.serotonin.mango.web.servlet;

import java.io.IOException;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.serotonin.mango.Common;
import com.serotonin.mango.vo.User;

/**
 * @author Matthew Lohbihler
 */
public class ReportChartServlet extends BaseInfoServlet {
    private static final long serialVersionUID = -1;

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
        // The only place that should be calling this servlet is the report chart, generated by a Freemarker
        // template. The ReportChartCreator that controlled the generation put the generated image content into the
        // user object, so all i need to do is write that content to the response object.
        User user = Common.getUser(request);
        if (user != null) {
            Map<String, byte[]> imageData = user.getReportImageData();
            if (imageData != null) {
                String path = request.getPathInfo();

                // Path will be of the format "/<chartName>", so we need to ignore the first character.
                byte[] data = imageData.get(path.substring(1));
                if (data != null)
                    response.getOutputStream().write(data);
            }
        }
    }
}

WebContent/WEB-INF/ftl/report/reportChart.ftl
<#--
    Mango - Open Source M2M - http://mango.serotoninsoftware.com
    Copyright (C) 2006-2011 Serotonin Software Technologies Inc.
    @author Matthew Lohbihler
    
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see http://www.gnu.org/licenses/.
-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html>
<head>
  <title><@fmt key="header.title"/></title>
  
  <!-- Meta -->
  <meta http-equiv="content-type" content="application/xhtml+xml;charset=utf-8"/>
  <meta http-equiv="Content-Style-Type" content="text/css" />
  <meta name="Copyright" content="&copy;2006-2011 Serotonin Software Technologies Inc."/>
  
  <!-- Style -->
  <link rel="icon" href="images/favicon.ico"/>
  <link rel="shortcut icon" href="images/favicon.ico"/>
  <style type="text/css">
    .bod {
      margin: 10px;
      padding: 5px;
      background-color: #FFFFFF;
    }
    .bod, td, th {
      font-family: Verdana, Arial, Helvetica, sans-serif;
      font-size: 11px;
      color: #000000;
    }
    .pointName {
      color: #804000;
      font-size: 13px;
      font-weight: bold;
    }
    .label {
      font-weight: bold;
      text-align: right;
      padding-right: 10px;
    }
    .stats {
      background-color: #F0F0F0;
      vertical-align: top;
    }
    .rowHeader td {
      font-weight: bold;
      color: #FFFFFF;
      background-color: #F07800;
      text-align: center;
      white-space: nowrap;
      padding: 3px 10px 3px 10px;
    }
    .row td, .rowAlt td {
      color: #000000;
      padding: 3px;
    }
    .row td {
      background-color: #F0F0F0;
    }
    .rowAlt td {
      background-color: #DCDCDC;
    }
    .copyTitle {
      color: #804000;
      font-size: 10px;
    }
  </style>
</head>

<body>
<div class="bod">
  <table width="100%" cellspacing="0" cellpadding="0" border="0">
    <tr>
      <td>
        <table>
          <tr>
            <td colspan="2"><h1>${instance.name}</h1></td>
          </tr>
          <tr>
            <td class="label"><@fmt key="reports.runTimeStart"/></td>
            <td>${instance.prettyRunStartTime}</td>
          </tr>
          <tr>
            <td class="label"><@fmt key="reports.runDuration"/></td>
            <td>${instance.prettyRunDuration}</td>
          </tr>
          <tr>
            <td class="label"><@fmt key="reports.dateRange"/></td>
            <td>${instance.prettyReportStartTime} <@fmt key="reports.dateRangeTo"/> ${instance.prettyReportEndTime}</td>
          </tr>
          <tr>
            <td class="label"><@fmt key="reports.reportRecords"/></td>
            <td>${instance.prettyRecordCount}</td>
          </tr>
        </table>
      </td>
      <td valign="top" align="right"><img src="${inline}<@img src="mangoLogoMed.jpg"/>" alt="Logo"/></td>
    </tr>
  </table>

  <h2><@fmt key="reports.statistics"/></h2>
  <table cellspacing="5">
    <#assign col = 1/>
    <#list points as point>
      <#assign col = col + 1/>
      <#if col == 2><#assign col = 0/></#if>
      <#if col == 0><tr></#if>
      
      <td class="stats">
        <table>
          <tr><td colspan="2" class="pointName">${point.name}</td></tr>
          <tr>
            <td class="label"><@fmt key="reports.dataType"/></td>
            <td>${point.dataTypeDescription}</td>
          </tr>
          <#if point.startValue??>
            <tr>
              <td class="label"><@fmt key="common.stats.start"/></td>
              <td>${point.startValue}</td>
            </tr>
          </#if>
          <#if point.dataType == NUMERIC>
            <tr>
              <td class="label"><@fmt key="common.stats.min"/></td>
              <td>${point.analogMinimum} @ ${point.analogMinTime}</td>
            </tr>
            <tr>
              <td class="label"><@fmt key="common.stats.max"/></td>
              <td>${point.analogMaximum} @ ${point.analogMaxTime}</td>
            </tr>
            <tr>
              <td class="label"><@fmt key="common.stats.avg"/></td>
              <td>${point.analogAverage}</td>
            </tr>
            <tr>
              <td class="label"><@fmt key="common.stats.sum"/></td>
              <td>${point.analogSum}</td>
            </tr>
            <tr>
              <td class="label"><@fmt key="common.stats.count"/></td>
              <td>${point.analogCount}</td>
            </tr>
          <#elseif point.dataType == BINARY || point.dataType == MULTISTATE>
            <tr>
              <td colspan="2">
                <table>
                  <tr style="padding-top:15px">
                    <th><@fmt key="common.stats.value"/></th>
                    <th><@fmt key="common.stats.starts"/></th>
                    <th><@fmt key="common.stats.runtime"/></th>
                  </tr>
                  
                  <#list point.startsAndRuntimes as sar>
                    <tr>
                      <td>${sar.value}</td>
                      <td align="right">${sar.starts}</td>
                      <td align="right">${sar.runtime}</td>
                    </tr>
                  </#list>
                </table>
              </td>
            </tr>
          <#elseif point.dataType == ALPHANUMERIC || point.dataType == IMAGE>
            <tr>
              <td class="label"><@fmt key="common.stats.count"/></td>
              <td>${point.valueChangeCount}</td>
            </tr>
          </#if>
          <#if point.chartData>
            <tr>
              <td colspan="2"><img src="${inline}${point.chartPath}"/></td>
            </tr>
          </#if>
        </table>
      </td>
      
      <#if col == 1></tr></#if>
    </#list>
    <#if col < 1></tr></#if>
  </table>
  
  <#if chartName??>
    <h2><@fmt key="reports.consolidated"/></h2>
    <img src="${inline}${chartName}"/>
  </#if>
  
  <#if includeEvents>
    <h2><@fmt key="reports.events"/></h2>
    <#if events?size == 0>
      <@fmt key="events.emptyList"/>
    <#else>
      <table cellspacing="1" cellpadding="0" width="100%">
        <tr class="rowHeader">
          <td><@fmt key="reports.eventList.id"/></td>
          <td><@fmt key="common.alarmLevel"/></td>
          <td><@fmt key="common.activeTime"/></td>
          <td><@fmt key="reports.eventList.message"/></td>
          <td><@fmt key="reports.eventList.status"/></td>
          <td><@fmt key="events.acknowledged"/></td>
        </tr>
        
        <#assign row = 1/>
        <#list events as event>
          <#assign row = row + 1/>
          <#if row == 2><#assign row = 0/></#if>
          
          <tr class="row<#if row == 1>Alt</#if>">
            <td align="center">${event.id?c}</td>
            <td align="center">
              <#if event.alarmLevel == 0><img src="${inline}<@img src="flag_green.png"/>" alt="<@fmt key="common.alarmLevel.none"/>"/>
              <#elseif event.alarmLevel == 1><img src="${inline}<@img src="flag_blue.png"/>" alt="<@fmt key="common.alarmLevel.info"/>"/>
              <#elseif event.alarmLevel == 2><img src="${inline}<@img src="flag_yellow.png"/>" alt="<@fmt key="common.alarmLevel.urgent"/>"/>
              <#elseif event.alarmLevel == 3><img src="${inline}<@img src="flag_orange.png"/>" alt="<@fmt key="common.alarmLevel.critical"/>"/>
              <#elseif event.alarmLevel == 4><img src="${inline}<@img src="flag_red.png"/>" alt="<@fmt key="common.alarmLevel.lifeSafety"/>"/>
              <#else>(<@fmt key="common.alarmLevel.unknown"/>  ${event.alarmLevel})
              </#if>
            </td>
            <td>${event.fullPrettyActiveTimestamp}</td>
            <td>
              <b><@fmt message=event.message/></b>
              <#if event.eventComments??>
                <table cellspacing="0" cellpadding="0">
                  <#list event.eventComments as comment>
                    <tr>
                      <td valign="top" width="16"><img src="${inline}<@img src="comment.png"/>" alt="<@fmt key="notes.note"/>"/></td>
                      <td valign="top">
                        <span class="copyTitle">
                          ${comment.prettyTime} <@fmt key="notes.by"/>
                          <#if comment.username??>
                            ${comment.username}
                          <#else>
                            <@fmt key="common.deleted"/>
                          </#if>
                        </span><br/>
                        ${comment.comment}
                      </td>
                    </tr>
                  </#list>
                </table>
              </#if>
            </td>
            <td>
              <#if event.active>
                <@fmt key="common.active"/>
                <img src="${inline}<@img src="flag_white.png"/>" alt="<@fmt key="common.active"/>"/>
              <#elseif !event.rtnApplicable>
              <#else>
                ${event.fullPrettyRtnTimestamp} - <@fmt message=event.rtnMessage/>
              </#if>
            </td>
            <td>
              <#if event.acknowledged>
                ${event.fullPrettyAcknowledgedTimestamp}
                <@fmt message=event.ackMessage/>
              </#if>
            </td>
          </tr>
        </#list>
      </table>
    </#if>
  </#if>
  
  <#if includeUserComments>
    <h2><@fmt key="reports.pointComments"/></h2>
    <#if userComments?size == 0>
      <@fmt key="reports.pointComments.empty"/>
    <#else>
      <table cellspacing="0" cellpadding="0">
        <#list userComments as comment>
          <tr>
            <td valign="top" width="16"><img src="${inline}<@img src="comment.png"/>" alt="<@fmt key="notes.note"/>"/></td>
            <td valign="top">
              <span class="copyTitle">
                ${comment.prettyTime} <@fmt key="notes.by"/>
                <#if comment.username??>
                  ${comment.username},
                <#else>
                  <@fmt key="common.deleted"/>,
                </#if>
                '${comment.pointName}'
              </span><br/>
              ${comment.comment}
            </td>
          </tr>
        </#list>
      </table>
    </#if>
  </#if>
</div>

<table width="100%" cellspacing="0" cellpadding="0" border="0">
  <tr><td colspan="2">&nbsp;</td></tr>
  <tr>
    <td colspan="2" class="footer" align="center">&copy;2006-2011 Serotonin Software Technologies Inc., <@fmt key="footer.rightsReserved"/></td>
  </tr>
</table>

</body>
</html>